# config/database.yml

default: &default
  adapter: oracle_enhanced
  username: ROBERTO
  password: ROBERTO$P
  host: 44.200.174.128 # O la IP o hostname del servidor de Oracle
  port: 1521
  database: PREPROD # SID de la base de datos Oracle
  encoding: utf8

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

