# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: oracle_enhanced
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: utf8
  database: //keruxdb:1521/PREPROD
  username: SYSTEM
  password: SYSTEM

test:
  encoding: utf8
  database: //keruxdb:1521/PREPROD
  username: SYSTEM
  password: SYSTEM

production:
  encoding: utf8
  database: //keruxdb:1521/PREPROD
  username: SYSTEM
  password: SYSTEM
