source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 6.1.1"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use oracle as the database for Active Record
gem "activerecord-oracle_enhanced-adapter" # Adaptador para Oracle
gem "ruby-oci8" # Dependencia para el adaptador de Oracle
gem "ruby-plsql" # Integración de PL/SQL con Ruby
gem "composite_primary_keys", "~> 13.0", source: "https://rubygems.org" # una biblioteca que proporciona validaciones de modelo para Active Storage en Rails.
gem "active_storage_validations" # una biblioteca que proporciona validaciones de modelo para Active Storage en Rails.

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"
gem "redis", "~> 4.0" # gestión de caché y en la implementación de Action Cable.
gem "bootsnap", ">= 1.4.2", require: false
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "byebug" # Debugger para Ruby
  gem "multi_config" # Manejar diferentes archivos de configuración
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end
gem "rack-cors"
gem "jbuilder" # Crear estructuras JSON de forma fácil
